vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
       media:
           uri_prefix: /upload
           upload_destination: '%kernel.project_dir%/public/upload'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
